server:
  bind: 127.0.0.1:3000
  tls:
    cert_file: localhost.crt
    key_file: localhost.key

filters:
  - anonymous:
      paths:
        - "/static/**"
        - "/heathcheck"
        - "/int-api/**"

  - form_login:
      path: /login
      success_redirect: /
      failure_redirect: /login
      user_base: &userbase
        user_pass:
          users:
            - ["alice", "123456"]
            - ["bob", "asdf"]

  - cookie_session:
      public_key_file: public.pem

  - basic:
      user_base: *userbase

  - redirect:
      location: /login

session:
  private_key: private.pem

target:
  url: http://localhost:8080/
