server:
  bind: 127.0.0.1:3000
  tls:
    cert_file: localhost.crt
    key_file: localhost.key

filters:
  - anonymous:
      paths:
        - "/static/**"

  - form_login:
      path: /login
      success_redirect: /
      failure_redirect: /login
      user_base:
        user_pass: &userbase
          users:
            - ["admin", "password"]
            - ["user", "asdfasdf"]

  - cookie_session:

  - basic:
      user_base: *userbase

  - redirect:
      location: /login

session:
  private_key_file: private.pem
  public_key_file: public.pem

target:
  url: http://localhost:8080/
