server:
  bind: 127.0.0.1:3000
  tls:
    cert_file: localhost.crt
    key_file: localhost.key

filters:
  - anonymous:
      paths:
        - "/static/**"
        - "/int-api/**"
        - "/healthcheck"

#  - form_login:
#      path: /login
#      user_base:
#        ldap:
#          url: "ldap://localhost:10389/"
#          base_dn: "ou=people,dc=planetexpress,dc=com"

#        user_pass:
#          users:
#            - ["admin", "password"]
#            - ["user", "asdfasdf"]

  - cookie_session:

  - basic:
      user_base:
        ldap:
          url: "ldap://localhost:10389/"
          base_dn: "ou=people,dc=planetexpress,dc=com"

  - redirect:
      location: /login

session:
  private_key_file: private.pem
  public_key_file: public.pem

target:
  url: http://localhost:8080/
