server:
  bind: 127.0.0.1:3000
  tls:
    cert_file: localhost.crt
    key_file: localhost.key

filters:
  - anonymous:
      paths:
        - "/anon/**"

  - form_login:
      path: /login
      user_base: &user_base
        user_pass:
          users:
            - [fry, seymour]
        # ldap:
        #   url: "ldap://localhost:10389/"
        #   base_dn: "ou=people,dc=planetexpress,dc=com"

  - cookie_session:

  - basic:
      user_base: *user_base

  - redirect:
      location: /login

session:
  private_key_file: private.pem
  public_key_file: public.pem

target:
  url: http://localhost:10000/
