server:
  bind: 0.0.0.0:8080
  tls:
    cert_file: /etc/sealproxy/localhost.crt
    key_file: /etc/sealproxy/localhost.key

filters:
  - anonymous:
      paths:
        - "/anon/**"

  - oauth2:
      path: /login
      redirect_url: "https://localhost:8080/oauth2/callback"
      auth_url: "http://localhost:5556/dex/auth"
      token_url: "http://dex:5556/dex/token"
      userinfo_url: "http://dex:5556/dex/userinfo"
      client_id: "seal"
      client_secret: "NmJkYjQzMTA1OWQwYzFjMjVhMTEyYzZhYzUwMTczYzVkMzVhMDVhYwo="
      scopes:
        - "openid"
        - "profile"
      success_redirect: "/"

  - cookie_session:

  - redirect:
      location: /login

session:
  private_key_file: /etc/sealproxy/private.pem
  public_key_file: /etc/sealproxy/public.pem

target:
  url: http://echo-server:8080/
