version: '3.9'
services:
  sealproxy:
    image: sealproxy:local
    command: ["-c", "/etc/sealproxy/sealproxy.yml"]
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/etc/sealproxy/sealproxy.yml:ro
      - ./localhost.crt:/etc/sealproxy/localhost.crt:ro
      - ./localhost.key:/etc/sealproxy/localhost.key:ro
      - ./private.pem:/etc/sealproxy/private.pem:ro
      - ./public.pem:/etc/sealproxy/public.pem:ro
    env_file:
      - .env
    restart: unless-stopped

  dex:
    image: dexidp/dex:latest
    ports:
      - "5556:5556"
    volumes:
      - ./dex-config.yml:/etc/dex/config.yml
      - ldap_ssl:/etc/ldap/ssl
    command: ["dex", "serve", "/etc/dex/config.yml"]
    depends_on:
      - openldap # allow openldap to create the TLS certificate before starting

  openldap:
    image: ghcr.io/rroemhild/docker-test-openldap
    ports:
      - "10636:10636"
    volumes:
      - ldap_ssl:/etc/ldap/ssl
    restart: unless-stopped

  echo-server:
    image: jmalloc/echo-server
    ports:
      - "10000:8080"
    restart: unless-stopped

volumes:
  ldap_ssl:
